[package]
edition = "2021"
name = "rustvaders"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "~0.8"
crossterm = "~0.20"
rusty_audio = "^1.2"
rusty_time = "~0.11"
